[package]
name = "td_clua"
version = "0.1.3"
authors = ["wugd"]
description = "Bindings for Lua 5.3"
repository = "https://github.com/tickbh/td_rlua"
build = "build.rs"
links = "lua"
license = "MIT/Apache-2.0"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"

[dependencies]
libc = "^0.2.1"
